# Generated by Django 5.0.1 on 2024-11-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_arm_style_remove_product_assembly_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured_image',
            new_name='image',
        ),
    ]
