# Generated by Django 5.0.1 on 2024-11-15 23:38

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=1255)),
                ('description', models.TextField(max_length=1255)),
                ('image', models.ImageField(upload_to='images/')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('status', models.CharField(choices=[('Complate', 'Complate'), ('Ongoing', 'Ongoing'), ('Upcoming', 'Upcoming')], max_length=10)),
                ('featured_project', models.BooleanField(default=False)),
                ('Top_Deals_Of_The_Day', models.BooleanField(default=False)),
                ('Top_Selling_Products', models.BooleanField(default=False)),
                ('Recommended_For_You', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '2. Project',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=1255)),
                ('description', models.TextField(max_length=1255)),
                ('image', models.ImageField(upload_to='images/')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('featured_project', models.BooleanField(default=False)),
                ('Top_Deals_Of_The_Day', models.BooleanField(default=False)),
                ('Top_Selling_Products', models.BooleanField(default=False)),
                ('Recommended_For_You', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '3. Service',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '4. Comment'},
        ),
        migrations.CreateModel(
            name='Project_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.project')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.service')),
            ],
        ),
    ]
