# Generated by Django 5.0.1 on 2024-11-16 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_project_service_alter_comment_options_project_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Recommended_For_You',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Top_Deals_Of_The_Day',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Top_Selling_Products',
        ),
    ]
