# Generated by Django 5.0.1 on 2024-11-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_service_recommended_for_you_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Recommended_For_You',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Top_Deals_Of_The_Day',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Top_Selling_Products',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('COMPLATE', 'COMPLATE'), ('ONGOING', 'ONGOING'), ('UPCOMING', 'UPCOMING')], max_length=10),
        ),
    ]
