# Generated by Django 5.0.1 on 2024-11-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='sub_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
