# Generated by Django 5.0.1 on 2024-11-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about_page_experience_about_page_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '11. Content_Slider',
            },
        ),
    ]
