# Generated by Django 5.0.1 on 2024-11-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_content_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
