# Generated by Django 5.0.1 on 2024-11-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_setting_address_alter_setting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='some_faq_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
