# Generated by Django 5.0.1 on 2024-11-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_faq_ordernumber_alter_faq_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='OurServices_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='product_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
