# Generated by Django 5.0.1 on 2025-01-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_setting_ourservices_title_setting_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('sub_title', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '10. Gallery Page',
            },
        ),
    ]
