# Generated by Django 5.0.1 on 2024-10-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('icone_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '19. Social Site',
            },
        ),
    ]
